name: CI demonstration

on:
  merge_group:

jobs:
  test:
    name: Test merge queues
    runs-on: ubuntu-latest

    steps:
      - name: Check commit ${{ github.sha }}
        run: |
          echo "Hello, world!"
          echo "Thinking..."

          sleep 30

          echo "Done!"

          exit 1
